let books = [
  {
		id : '0',  
    title : 'Les Misérables 1',
		author : 'Victor Hugo',
		price : 14.95,
		category : 'Drame',
		releaseDate : new Date('1997-05-23'),
		nbSales : 124,
		nbStock : 150,
  },
	{
		id : '1',  
    title : 'Fight Club',
		author : 'Chuck Palahniuk',
		price : 9.99,
		category : 'Drame',
		releaseDate : new Date('1996-01-14'),
		nbSales : 365,
		nbStock : 237,
	},
	{
		id : '2',  
    title : 'Les Misérables 2',
		author : 'Victor Hugo',
		price : 14.95,
		category : 'Drame',
		releaseDate : new Date('1997-05-23'),
		nbSales : 345,
		nbStock : 0,
	},
];